# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: '3.9'
services:
  chrome:
    image: selenium/node-chrome:3.141.59-zirconium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    extra_hosts:
      - "localhost.host:${HOST_IP}"

  firefox:
    image: selenium/node-firefox:3.141.59-zirconium
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
    extra_hosts:
      - "localhost.host:${HOST_IP}"

  hub:
    image: selenium/hub:3.141.59-zirconium
    ports:
      - "4444:4444"
    depends_on:
      - jenkins

  jenkins:
    image: jenkins/jenkins:lts
    user: root
    hostname: jenkins123
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - "/home/runner/work/JenkinsQA/JenkinsQA/selenium-grid/var/jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - JENKINS_HOME=/var/jenkins_home