name: CI

on:
  pull_request:
    branches: [main]

jobs:
  run-test:
    name: 'Run Tests'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - uses: actions/cache@v2
        with:
          path: /home/runner/work/JenkinsQA/JenkinsQA/selenium-grid
          key: ${{ runner.os }}-jenkins_backup-${{ hashFiles('**/jenkins_backup.tar') }}
          restore-keys: ${{ runner.os }}-jenkins_backup-

      - name: Public IP
        id: ip
        uses: haythem/public-ip@v1.2

#      - name: Docker login
#        run: echo ${{ secrets.DOCKER_PAS }} | docker login --username ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Docker start
        run: docker-compose -f ./selenium-grid/docker-compose.yml up -d
        env:
          HOST_IP: ${{ steps.ip.outputs.ipv4 }}

      - name: Wait Grid is UP
        run: ./selenium-grid/wait-for-grid.sh

      - name: Load Jenkins data
        run: |
         if [ ! -f /home/runner/work/JenkinsQA/JenkinsQA/selenium-grid/jenkins_backup.tar ]; then
               curl http://buildemojis.com/jenkins_backup.tar -o /home/runner/work/JenkinsQA/JenkinsQA/selenium-grid/jenkins_backup.tar
         fi

      - name: Insatll Jenkins data
        run: |
          docker run --rm --volumes-from jenkins-container -v /home/runner/work/JenkinsQA/JenkinsQA/selenium-grid:/backup ubuntu bash -c "cd /var && tar xf /backup/jenkins_backup.tar --strip 1"
          docker restart jenkins-container
          sleep 120

      - name: Maven test
        run: mvn test

      - name: Docker stop
        run: docker-compose -f ./selenium-grid/docker-compose.yml down
